import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang='pt'>
      <body>

        <main className={inter.className}>
          <Navbar></Navbar>
          {children}
          <Footer/>
          
        </main>
      </body>
    </html>
    // <html lang="en">
    //   <head>
    //     <div>
    //       <Navbar></Navbar>
    //     </div>
    //   </head>
    //   <body className={inter.className}>{children}</body>
    // </html>
  )
}
